import { tag } from './createElement.js';

export const button = tag('button');
export const span = tag('span');
export const div = tag('div');
export const textarea = tag('textarea');

export const nums = [
  {
    key: '`',
    keyShift: '~',
    keyCode: 'Backquote',
    key2ndLang: 'ё',
    keyShift2ndLang: 'Ё',
  },
  {
    key: '1',
    keyShift: '!',
    keyCode: 'Digit1',
    key2ndLang: '1',
    keyShift2ndLang: '!',
  },
  {
    key: '2',
    keyShift: '@',
    keyCode: 'Digit2',
    key2ndLang: '2',
    keyShift2ndLang: '"',
  },
  {
    key: '3',
    keyShift: '#',
    keyCode: 'Digit3',
    key2ndLang: '3',
    keyShift2ndLang: '№',
  },
  {
    key: '4',
    keyShift: '$',
    keyCode: 'Digit4',
    key2ndLang: '4',
    keyShift2ndLang: ';',
  },
  {
    key: '5',
    keyShift: '%',
    keyCode: 'Digit5',
    key2ndLang: '5',
    keyShift2ndLang: '%',
  },
  {
    key: '6',
    keyShift: '^',
    keyCode: 'Digit6',
    key2ndLang: '6',
    keyShift2ndLang: ':',
  },
  {
    key: '7',
    keyShift: '&',
    keyCode: 'Digit7',
    key2ndLang: '7',
    keyShift2ndLang: '?',
  },
  {
    key: '8',
    keyShift: '*',
    keyCode: 'Digit8',
    key2ndLang: '8',
    keyShift2ndLang: '*',
  },
  {
    key: '9',
    keyShift: '(',
    keyCode: 'Digit9',
    key2ndLang: '9',
    keyShift2ndLang: '(',
  },
  {
    key: '0',
    keyShift: ')',
    keyCode: 'Digit0',
    key2ndLang: '0',
    keyShift2ndLang: ')',
  },
  {
    key: '-',
    keyShift: '_',
    keyCode: 'Minus',
    key2ndLang: '-',
    keyShift2ndLang: '_',
  },
  {
    key: '=',
    keyShift: '+',
    keyCode: 'Equal',
    key2ndLang: '=',
    keyShift2ndLang: '+',
  },
];

export const letters1 = [
  {
    key: 'q',
    keyShift: 'Q',
    keyCode: 'KeyQ',
    key2ndLang: 'й',
    keyShift2ndLang: 'Й',
  },
  {
    key: 'w',
    keyShift: 'W',
    keyCode: 'KeyW',
    key2ndLang: 'ц',
    keyShift2ndLang: 'Ц',
  },
  {
    key: 'e',
    keyShift: 'E',
    keyCode: 'KeyE',
    key2ndLang: 'у',
    keyShift2ndLang: 'У',
  },
  {
    key: 'r',
    keyShift: 'R',
    keyCode: 'KeyR',
    key2ndLang: 'к',
    keyShift2ndLang: 'К',
  },
  {
    key: 't',
    keyShift: 'T',
    keyCode: 'KeyT',
    key2ndLang: 'е',
    keyShift2ndLang: 'Е',
  },
  {
    key: 'y',
    keyShift: 'Y',
    keyCode: 'KeyY',
    key2ndLang: 'н',
    keyShift2ndLang: 'Н',
  },
  {
    key: 'u',
    keyShift: 'U',
    keyCode: 'KeyU',
    key2ndLang: 'г',
    keyShift2ndLang: 'Г',
  },
  {
    key: 'i',
    keyShift: 'I',
    keyCode: 'KeyI',
    key2ndLang: 'ш',
    keyShift2ndLang: 'Ш',
  },
  {
    key: 'o',
    keyShift: 'O',
    keyCode: 'KeyO',
    key2ndLang: 'щ',
    keyShift2ndLang: 'Щ',
  },
  {
    key: 'p',
    keyShift: 'P',
    keyCode: 'KeyP',
    key2ndLang: 'з',
    keyShift2ndLang: 'З',
  },
  {
    key: '[',
    keyShift: '{',
    keyCode: 'BracketLeft',
    key2ndLang: 'х',
    keyShift2ndLang: 'Х',
  },
  {
    key: ']',
    keyShift: '}',
    keyCode: 'BracketRight',
    key2ndLang: 'ъ',
    keyShift2ndLang: 'Ъ',
  },
];

export const letters2 = [
  {
    key: 'a',
    keyShift: 'A',
    keyCode: 'KeyA',
    key2ndLang: 'ф',
    keyShift2ndLang: 'Ф',
  },
  {
    key: 's',
    keyShift: 'S',
    keyCode: 'KeyS',
    key2ndLang: 'ы',
    keyShift2ndLang: 'Ы',
  },
  {
    key: 'd',
    keyShift: 'D',
    keyCode: 'KeyD',
    key2ndLang: 'в',
    keyShift2ndLang: 'В',
  },
  {
    key: 'f',
    keyShift: 'F',
    keyCode: 'KeyF',
    key2ndLang: 'а',
    keyShift2ndLang: 'А',
  },
  {
    key: 'g',
    keyShift: 'G',
    keyCode: 'KeyG',
    key2ndLang: 'п',
    keyShift2ndLang: 'П',
  },
  {
    key: 'h',
    keyShift: 'H',
    keyCode: 'KeyH',
    key2ndLang: 'р',
    keyShift2ndLang: 'Р',
  },
  {
    key: 'j',
    keyShift: 'J',
    keyCode: 'KeyJ',
    key2ndLang: 'о',
    keyShift2ndLang: 'О',
  },
  {
    key: 'k',
    keyShift: 'K',
    keyCode: 'KeyK',
    key2ndLang: 'л',
    keyShift2ndLang: 'Л',
  },
  {
    key: 'l',
    keyShift: 'L',
    keyCode: 'KeyL',
    key2ndLang: 'д',
    keyShift2ndLang: 'Д',
  },
  {
    key: ';',
    keyShift: ':',
    keyCode: 'Semicolon',
    key2ndLang: 'ж',
    keyShift2ndLang: 'Ж',
  },
  {
    key: "'",
    keyShift: '"',
    keyCode: 'Quote',
    key2ndLang: 'э',
    keyShift2ndLang: 'Э',
  },
];

export const letters3 = [
  {
    key: 'z',
    keyShift: 'Z',
    keyCode: 'KeyZ',
    key2ndLang: 'я',
    keyShift2ndLang: 'Я',
  },
  {
    key: 'x',
    keyShift: 'X',
    keyCode: 'KeyX',
    key2ndLang: 'ч',
    keyShift2ndLang: 'Ч',
  },
  {
    key: 'c',
    keyShift: 'C',
    keyCode: 'KeyC',
    key2ndLang: 'с',
    keyShift2ndLang: 'С',
  },
  {
    key: 'v',
    keyShift: 'V',
    keyCode: 'KeyV',
    key2ndLang: 'м',
    keyShift2ndLang: 'М',
  },
  {
    key: 'b',
    keyShift: 'B',
    keyCode: 'KeyB',
    key2ndLang: 'и',
    keyShift2ndLang: 'И',
  },
  {
    key: 'n',
    keyShift: 'N',
    keyCode: 'KeyN',
    key2ndLang: 'т',
    keyShift2ndLang: 'Т',
  },
  {
    key: 'm',
    keyShift: 'M',
    keyCode: 'KeyM',
    key2ndLang: 'ь',
    keyShift2ndLang: 'Ь',
  },
  {
    key: ',',
    keyShift: '<',
    keyCode: 'Comma',
    key2ndLang: 'б',
    keyShift2ndLang: 'Б',
  },
  {
    key: '.',
    keyShift: '>',
    keyCode: 'Period',
    key2ndLang: 'ю',
    keyShift2ndLang: 'Ю',
  },
  {
    key: '/',
    keyShift: '?',
    keyCode: 'Slash',
    key2ndLang: '.',
    keyShift2ndLang: ',',
  },
];
